---
title: "Positions"
title-block-banner: true
---

## PhD students

We are seeking [PhD students](https://www.janelia.org/you-janelia/students-and-postdocs/joint-graduate-programs) (through JHU) to investigate how large populations of neurons perform complex computations. We collect and analyze recordings of 50,000+ neurons, developing machine learning tools to extract computational principles from these large-scale datasets. Feel free to reach out to Carsen Stringer (<stringerc@hhmi.org>) with your CV if you are interested and have any questions. Applications should be submitted by **Dec 1 2024** to the [neuroscience department](https://neuroscience.jhu.edu/graduate) or the [XDBio department](https://xdbio.jhmi.edu/) at JHU. Fee waivers are available through the departments.  Please share a link to your github profile on your CV when applying.


All research is internally funded by the Howard Hughes Medical Institute with highly competitive benefits. For information about Janelia, please visit [www.janelia.org/about-us](http://www.janelia.org/about-us). For more information about our neuroscience department, please visit [www.janelia.org/our-research/mechanistic-cognitive-neuroscience](https://www.janelia.org/our-research/mechanistic-cognitive-neuroscience). For more information about being at Janelia, please check out these [videos](https://youtube.com/playlist?list=PLTHgpZlI_u0hSo_NO0wpzpMnt6BnOOaWl&feature=shared). Janelia provides incredible support for scientific research (surgical support, animal behavior training, and optical engineering), enabling researchers to focus on their specific scientific questions.

Diversity, equity and inclusion are important values at Janelia, and applicants should be dedicated to ensuring kindness and inclusion in their interactions with the scientific community and with other employees at Janelia. See more details about HHMI's commitment to diversity here: <https://diversity.hhmi.org/>.
