---
title: "Publications"
toc: true
title-block-banner: true
sidebar: true
---

### preprints

Marius Pachitariu, Michael Rariden, Carsen Stringer. [Cellpose-SAM: superhuman generalization for cellular segmentation](https://www.biorxiv.org/content/10.1101/2025.04.28.651001v1). *bioRxiv*, 2025.

Marius Pachitariu, Lin Zhong, Alexa Gracias, Amanda Minisi, Crystall Lopez, Carsen Stringer. [A critical initialization for biological neural networks](https://www.biorxiv.org/content/10.1101/2025.01.10.632397.abstract). *bioRxiv*, 2025.

Jason A Keller, Iljung S Kwak, Alyssa K Stark, Marius Pachitariu, Kristin Branson, Joshua T Dudman. [Cortical control of innate behavior from subcortical demonstration](Cortical control of innate behavior from subcortical demonstration). *bioRxiv*, 2025.

Judith Hoeller, Lin Zhong, Marius Pachitariu, Sandro Romani. [Bridging tuning and invariance with equivariant neuronal representations](https://www.biorxiv.org/content/10.1101/2024.08.02.606398v1.abstract). *bioRxiv*, 2024.

Carsen Stringer, Marius Pachitariu. [Benchmarking cellular segmentation methods against Cellpose](https://www.biorxiv.org/content/10.1101/2024.04.06.587952v2). *bioRxiv*, 2024.

Yuki Miura, Ji-il Kim, Ovidiu Jurjut, Kevin W Kelley, Xiao Yang, Xiaoyu Chen, Mayuri Vijay Thete, Omer Revah, Bianxiao Cui, Marius Pachitariu, Sergiu P Pasca. [Assembloid model to study loop circuits of the human nervous system](https://www.biorxiv.org/content/10.1101/2024.10.13.617729.abstract). *bioRxiv*, 2024.

Leandro PL Jacob, Sydney M Bailes, Stephanie D Williams, Carsen Stringer, Laura D Lewis. [Distributed fMRI dynamics predict distinct EEG rhythms across sleep and wakefulness](https://www.biorxiv.org/content/10.1101/2024.01.29.577429v2). *bioRxiv*, 2024.

Stefanos Stagkourakis, Giada Spigolon, Markus Marks, Michael Feyder, Joseph Kim, Pietro Perona, Marius Pachitariu, David J Anderson. [Anatomically distributed neural representations of instincts in the hypothalamus](https://www.biorxiv.org/content/10.1101/2023.11.21.568163v2). *bioRxiv*, 2023.

### 2025

Fengtong Du, Miguel Angel Núñez-Ochoa, Marius Pachitariu<sup>†</sup>, Carsen Stringer<sup>†</sup>. [A simplified minimodel of visual cortical neurons](https://www.nature.com/articles/s41467-025-61171-9). *Nature Communications*, 2025.

Lin Zhong, Scott Baptista, Rachel Gattoni, Jon Arnold, Daniel Flickinger, Carsen Stringer<sup>†</sup>, Marius Pachitariu<sup>†</sup>. [Unsupervised pretraining in biological neural networks](https://www.nature.com/articles/s41586-025-09180-y) *Nature*, 2025.

Carsen Stringer, Marius Pachitariu. [Cellpose3: one-click image restoration for improved cellular segmentation](https://www.nature.com/articles/s41592-025-02595-5). *Nature Methods*, 2025.

Xuyu Qian, Kyle Coleman, Shunzhou Jiang, Andrea J Kriz, Jack H Marciano, Chunyu Luo, Chunhui Cai, Monica Devi Manam, Emre Caglayan, Aoi Otani, Urmi Ghosh, Diane D Shao, Rebecca E Andersen, Jennifer E Neil, Robert Johnson, Alexandra LeFevre, Jonathan L Hecht, Michael B Miller, Liang Sun, Carsen Stringer, Mingyao Li, Christopher A Walsh. [Spatial transcriptomics reveals human cortical layer and area specification](https://www.nature.com/articles/s41586-025-09010-1). *Nature*, 2025.

Valentina Gandin, Jun Kim, Liang-Zhong Yang, Yumin Lian, Takashi Kawase, Amy Hu, Konrad Rokicki, Greg Fleishman, Paul Tillberg, Alejandro Aguilera Castrejon, Carsen Stringer, Stephan Preibisch, Zhe J Liu. [Deep-Tissue Spatial Omics: Imaging Whole-Embryo Transcriptomics and Subcellular Structures at High Spatial Resolution](https://www.science.org/doi/10.1126/science.adq2084). *Science*, 2025.

Weinan Sun, Johan Winnubst, Maanasa Natrajan, Chongxi Lai, Koichiro Kajikawa, Michalis Michaelos, Rachel Gattoni, Carsen Stringer, Daniel Flickinger, James E Fitzgerald, Nelson Spruston. [Learning produces a hippocampal cognitive map in the form of an orthogonalized state machine](https://www.nature.com/articles/s41586-024-08548-w). *Nature*, 2025.


### 2024

Carsen Stringer, Marius Pachitariu. [Analysis methods for large-scale neuronal recordings](science.adp7429.pdf). *Science*, 2024.

Atika Syeda, Lin Zhong, Renee Tung, Will Long, Marius Pachitariu<sup>†</sup>, Carsen Stringer<sup>†</sup>. [Facemap: A Framework for Modeling Neural Activity Based on Orofacial Tracking](https://www.nature.com/articles/s41593-023-01490-6). *Nature Neuroscience*, 2024.

Marius Pachitariu, Shashwat Sridhar, Jacob Pennington, Carsen Stringer. [Spike sorting with Kilosort4](https://www.nature.com/articles/s41592-024-02232-7). *Nature Methods*, 2024.

Carsen Stringer, Lin Zhong, Atika Syeda, Fengtong Du, Maria Kesa, Marius Pachitariu. [Rastermap: A Discovery Method for Neural Population Recordings](https://www.nature.com/articles/s41593-024-01783-4). *Nature Neuroscience*, 2024.

Helen Farrants, Yichun Shuai, William C Lemon, Christian Monroy Hernandez, Shang Yang, Ronak Patel, Guanda Qiao, Michelle S Frei, Jonathan B Grimm, Timothy L Hanson, Filip Tomaska, Glenn C Turner, Carsen Stringer, Philipp J Keller, Abraham G Beyene, Yao Chen, Yajie Liang, Luke D Lavis, Eric R Schreiter. [A modular chemigenetic calcium indicator for multiplexed in vivo functional imaging](https://www.nature.com/articles/s41592-024-02411-6). *Nature Methods*, 2024.

### 2023

Jonathan W. Lovelace, Jingrui Ma, Saurabh Yadav, Karishma Chhabria, Hanbing Shen, Zhengyuan Pang, Tianbo Qi, Ruchi Sehgal, Yunxiao Zhang, Tushar Bali, Thomas Vaissiere, Shawn Tan, Yuejia Liu, Gavin Rumbaugh, Li Ye, David Kleinfeld, Carsen Stringer, Vineet Augustine. [Vagal sensory neurons mediate the Bezold–Jarisch reflex and induce syncope](https://www.nature.com/articles/s41586-023-06680-7). *Nature*, 2023.

### 2022

Marius Pachitariu, Carsen Stringer. [Cellpose 2.0: How to Train Your Own Model](https://www.nature.com/articles/s41592-022-01663-4). *Nature Methods* 19, no. 12 (2022): 1634--41. Research Briefing: [A Cellular Segmentation Algorithm with Fast Customization](https://www.nature.com/articles/s41592-022-01664-3).

Lilach Avitan, Carsen Stringer. [Not so Spontaneous: Multi-Dimensional Representations of Behaviors and Context in Sensory Areas](https://www.cell.com/neuron/pdf/S0896-6273(22)00588-8.pdf). *Neuron* 110, no. 19 (2022): 3064--75.

Kevin J Cutler, Carsen Stringer, Teresa W Lo, Luca Rappez, Nicholas Stroustrup, S Brook Peterson, Paul A Wiggins, Joseph D Mougous. [Omnipose: A High-Precision Morphology-Independent Solution for Bacterial Cell Segmentation](https://www.nature.com/articles/s41592-022-01639-4). *Nature Methods* 19, no. 11 (2022): 1438--48.

Richard J Gardner, Erik Hermansen, Marius Pachitariu, Yoram Burak, Nils A Baas, Benjamin A Dunn, May-Britt Moser, Edvard I Moser. [Toroidal Topology of Population Activity in Grid Cells](https://www.nature.com/articles/s41586-021-04268-7). *Nature* 602, no. 7895 (2022): 123--28.

Biraj Pandey, Marius Pachitariu, Bingni W. Brunton, and Kameron Decker Harris. [Structured Random Receptive Fields Enable Informative Sensory Encodings](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1010484). *PLoS Computational Biology* 18, no. 10 (2022): e1010484.

Bernard t Hart, Titipat Achakulvisut, Ayoade Adeyemi, Athena Akrami, Bradly Alicea, Alicia Alonso-Andres, Diego Alzate-Correa, ... Marius Pachitariu, ... Carsen Stringer, et al. [Neuromatch Academy: A 3-Week, Online Summer School in Computational Neuroscience](https://arrow.tudublin.ie/cgi/viewcontent.cgi?article=1358&context=scschmatart). *Journal of Open Source Education* 5, no. 49 (2022): 118.

Edward Zagha, Jeffrey C Erlich, Soohyun Lee, Gyorgy Lur, Daniel H O'Connor, Nicholas A Steinmetz, Carsen Stringer, Hongdian Yang. [The Importance of Accounting for Movement When Relating Neuronal Activity to Sensory and Cognitive Processes](https://www.jneurosci.org/content/42/8/1375.abstract). *Journal of Neuroscience* 42, no. 8 (2022): 1375--82.

### 2021

Carsen Stringer, Michalis Michaelos, Dmitri Tsyboulski, Sarah E Lindo, Marius Pachitariu. [High-Precision Coding in Visual Cortex](https://www.cell.com/cell/pdf/S0092-8674(21)00373-1.pdf). *Cell* 184, no. 10 (2021): 2767--78.

Carsen Stringer, Tim Wang, Michalis Michaelos, Marius Pachitariu. [Cellpose: A Generalist Algorithm for Cellular Segmentation](https://www.nature.com/articles/s41592-020-01018-x). *Nature Methods* 18, no. 1 (2021): 100--106.

Nicholas A Steinmetz\*, Cagatay Aydin\*, Anna Lebedeva\*, Michael Okun\*, Marius Pachitariu\*, Marius Bauza, Maxime Beau, et al. [Neuropixels 2.0: A Miniaturized High-Density Probe for Stable, Long-Term Brain Recordings](https://www.science.org/doi/abs/10.1126/science.abf4588). *Science* 372, no. 6539 (2021): eabf4588.

Anne-Kathrin Eiselt, Susu Chen, Jim Chen, Jon Arnold, Tahnbee Kim, Marius Pachitariu, Scott M Sternson. [Hunger or Thirst State Uncertainty Is Resolved by Outcome Evaluation in Medial Prefrontal Cortex to Guide Decision-Making](https://www.nature.com/articles/s41593-021-00850-4). *Nature Neuroscience* 24, no. 7 (2021): 907--12.

Kyu Hyun Lee, Yu-Li Ni, Jennifer Colonell, Bill Karsh, Jan Putzeys, Marius Pachitariu, Timothy D Harris, Markus Meister. [Electrode Pooling Can Boost the Yield of Extracellular Recordings with Switchable Silicon Probes](https://www.nature.com/articles/s41467-021-25443-4). *Nature Communications* 12, no. 1 (2021): 5245.

Joshua H. Siegle, Xiaoxuan Jia, Séverine Durand, Sam Gale, Corbett Bennett, Nile Graddis, Greggory Heller, ..., Marius Pachitariu, et al. [Survey of Spiking in the Mouse Visual System Reveals Functional Hierarchy](https://www.nature.com/articles/s41586-020-03171-x). *Nature* 592, no. 7852 (2021): 86--92.

Tara van Viegen, Athena Akrami, Kathryn Bonnen, Eric DeWitt, Alexandre Hyafil, Helena Ledmyr, Grace W Lindsay, ... Carsen Stringer, ... Marius Pachitariu, et al. [Neuromatch Academy: Teaching Computational Neuroscience with Global Accessibility](https://www.cell.com/trends/cognitive-sciences/fulltext/S1364-6613(21)00095-4). *Trends in Cognitive Sciences* 25, no. 7 (2021): 535--38.

### 2020

Sylvia Schröder, Nicholas A Steinmetz, Michael Krumin, Marius Pachitariu, Matteo Rizzi, Leon Lagnado, Kenneth D Harris, Matteo Carandini. [Arousal Modulates Retinal Output](https://www.cell.com/neuron/pdf/S0896-6273(20)30318-4.pdf). *Neuron* 107, no. 3 (2020): 487--95.

### 2019

Carsen Stringer\*, Marius Pachitariu\*, Nicholas Steinmetz, Matteo Carandini<sup>†</sup>, Kenneth D Harris<sup>†</sup>. [High-Dimensional Geometry of Population Responses in Visual Cortex](https://www.nature.com/articles/s41586-019-1346-5). *Nature*, 2019, 1.

Carsen Stringer\*, Marius Pachitariu\*, Nicholas Steinmetz, Charu Bai Reddy, Matteo Carandini<sup>†</sup>, Kenneth D Harris<sup>†</sup>. [Spontaneous Behaviors Drive Multidimensional, Brainwide Activity](https://www.science.org/doi/abs/10.1126/science.aav7893). *Science* 364, no. 6437 (2019): 255.

Carsen Stringer, Marius Pachitariu. [Computational Processing of Neural Recordings from Calcium Imaging Data](https://www.sciencedirect.com/science/article/pii/S0959438818300977). *Current Opinion in Neurobiology* 55 (2019): 22--31.

William E. Allen, Michael Z. Chen, Nandini Pichamoorthy, Rebecca H. Tien, Marius Pachitariu, Liqun Luo, Karl Deisseroth. [Thirst Regulates Motivated Behavior through Modulation of Brainwide Neural Population Dynamics](https://www.science.org/doi/abs/10.1126/science.aav3932). *Science* 364, no. 6437 (2019): eaav3932.

### 2018

Marius Pachitariu, Carsen Stringer, Kenneth D Harris. [Robustness of Spike Deconvolution for Neuronal Calcium Imaging](https://www.jneurosci.org/content/38/37/7976.short). *Journal of Neuroscience* 38, no. 37 (2018): 7976--85.

Philipp Berens, Jeremy Freeman, Thomas Deneux, Nikolay Chenkov, Thomas McColgan, Artur Speiser, Jakob H Macke, ... Marius Pachitariu, et al. [Community-Based Benchmarking Improves Spike Rate Inference from Two-Photon Calcium Imaging Data](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006157). *PLoS Computational Biology* 14, no. 5 (2018): e1006157.

Mario Dipoppa, Adam Ranson, Michael Krumin, Marius Pachitariu, Matteo Carandini, Kenneth D. Harris. [Vision and Locomotion Shape the Interactions between Neuron Types in Mouse Visual Cortex](https://www.cell.com/neuron/pdf/S0896-6273(18)30243-5.pdf). *Neuron* 98, no. 3 (2018): 602--15.

### 2017

James J Jun, Nicholas A Steinmetz, Joshua H Siegle, Daniel J Denman, Marius Bauza, Brian Barbarits, Albert K Lee, ..., Marius Pachitariu, et al. [Fully Integrated Silicon Probes for High-Density Recording of Neural Activity](https://www.nature.com/articles/nature24636). *Nature* 551, no. 7679 (2017): 232--36.

### 2016

Marius Pachitariu, Nicholas Steinmetz, Shabnam Kadir, Matteo Carandini, Kenneth D Harris. [Kilosort: Realtime Spike-Sorting for Extracellular Electrophysiology with Hundreds of Channels](https://www.biorxiv.org/content/10.1101/061481.abstract). *bioRxiv*/*Neurips*, 2016.

Marius Pachitariu, Carsen Stringer, Sylvia Schröder, Mario Dipoppa, L Federico Rossi, Matteo Carandini, Kenneth D Harris. [Suite2p: Beyond 10,000 Neurons with Standard Two-Photon Microscopy](https://www.biorxiv.org/content/10.1101/061481.abstract). *bioRxiv*, 2016.

Carsen Stringer\*, Marius Pachitariu\*, Nicholas A Steinmetz, Michael Okun, Peter Bartho, Kenneth D Harris, Maneesh Sahani, Nicholas A Lesica. [Inhibitory Control of Correlated Intrinsic Variability in Cortical Networks](https://elifesciences.org/articles/19695). *Elife* 5 (2016): e19695.

### 2015

Marius Pachitariu, Dmitry R Lyamzin, Maneesh Sahani, Nicholas A Lesica. [State-Dependent Population Coding in Primary Auditory Cortex](https://www.jneurosci.org/content/35/5/2058.short). *Journal of Neuroscience* 35, no. 5 (2015): 2058--73.

Jasper Poort, Adil G. Khan, Marius Pachitariu, Abdellatif Nemri, Ivana Orsolic, Julija Krupic, Marius Bauza, et al. [Learning Enhances Sensory and Multiple Non-Sensory Representations in Primary Visual Cortex](https://www.cell.com/neuron/pdf/S0896-6273(15)00476-6.pdf). *Neuron* 86, no. 6 (2015): 1478--90.

### 2014

Ernesto Suárez, Steven Lettieri, Metthew C Zwier, Carsen Stringer, Sundar Raman Subramanian, Lillian T Chong, Daniel M Zuckerman. [Simultaneous Computation of Dynamical and Equilibrium Information Using a Weighted Ensemble of Trajectories](https://pubs.acs.org/doi/10.1021/ct401065r). *J. Chem. Theory Comput.* (2014), 10, 7, 2658–2667.

### 2013

Marius Pachitariu, Adam M Packer, Noah Pettit, Henry Dalgleish, Michael Hausser, Maneesh Sahani. [Extracting Regions of Interest from Biological Images with Convolutional Sparse Block Coding](https://proceedings.neurips.cc/paper_files/paper/2013/hash/1f50893f80d6830d62765ffad7721742-Abstract.html). In *Advances in Neural Information Processing Systems*, 1745--53, 2013.

Marius Pachitariu, Biljana Petreska, Maneesh Sahani. [Recurrent Linear Models of Simultaneously-Recorded Neural Populations](https://proceedings.neurips.cc/paper_files/paper/2013/hash/7895fc13088ee37f511913bac71fa66f-Abstract.html). *Advances in Neural Information Processing Systems* 26 (2013).

Marius Pachitariu, Maneesh Sahani. [Regularization and Nonlinearities for Neural Language Models: When Are They Needed?](https://arxiv.org/abs/1301.5650). *arXiv Preprint arXiv:1301. 5650*, 2013.

### 2012

Marius Pachitariu, Maneesh Sahani. [Learning Visual Motion in Recurrent Neural Networks](https://proceedings.neurips.cc/paper_files/paper/2012/file/0f96613235062963ccde717b18f97592-Paper.pdf). In *Neurips*, 1331--39, 2012.
